#include "class.h"

typedef struct _MESSAGE MESSAGE;

void MESSAGE_INIT(MESSAGE *);
void MESSAGE_PROC(MESSAGE *);
void MESSAGE_DESTROY(MESSAGE *);
void derp(void);

CLASS
(   MESSAGE,
    EXTEND(BASE)

	METHOD(print, ABSTRACT)
	METHOD(PROC, ABSTRACT)
	METHOD(DESTROY, ABSTRACT)
)
